### ISSUE TITLE
`__import__() argument 1 must be string, not module` using kotti_navigation git master with kotti master

### ISSUE THREAD

**Issue by msabramo** [Kotti/kotti_navigation#13]
I get `__import__() argument 1 must be string, not module` when I hit http://127.0.0.1:5000/

```pytb
  File "/Users/marca/python/virtualenvs/kotti_inventorysvc/lib/python2.7/site-packages/pyramid_chameleon/zpt.py", line 10, in renderer_factory
    return renderer.template_renderer_factory(info, ZPTTemplateRenderer)
  File "/Users/marca/python/virtualenvs/kotti_inventorysvc/lib/python2.7/site-packages/pyramid_chameleon/renderer.py", line 140, in template_renderer_factory
    return lookup(info)
  File "/Users/marca/python/virtualenvs/kotti_inventorysvc/lib/python2.7/site-packages/pyramid_chameleon/renderer.py", line 115, in __call__
    filename)
  File "/Users/marca/python/virtualenvs/kotti_inventorysvc/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1127, in resource_filename
    self, resource_name
  File "/Users/marca/dev/git-repos/pyramid/pyramid/config/assets.py", line 31, in get_resource_filename
    filename = overrides.get_filename(resource_name)
  File "/Users/marca/dev/git-repos/pyramid/pyramid/config/assets.py", line 125, in get_filename
    result = source.get_filename(path)
  File "/Users/marca/dev/git-repos/pyramid/pyramid/config/assets.py", line 224, in get_filename
    if pkg_resources.resource_exists(self.package, path):
  File "/Users/marca/python/virtualenvs/kotti_inventorysvc/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1116, in resource_exists
    return get_provider(package_or_requirement).has_resource(resource_name)
  File "/Users/marca/python/virtualenvs/kotti_inventorysvc/lib/python2.7/site-packages/pkg_resources/__init__.py", line 396, in get_provider
    __import__(moduleOrReq)
TypeError: __import__() argument 1 must be string, not module
```

```
[marca@marca-mac2 ~VIRTUAL_ENV]$ pip freeze 2> /dev/null | grep -i kotti
-e git+git@github.com:Kotti/Kotti.git@d1ff5594bf9ec05e20f68c2343fb12278fc47f6b#egg=Kotti-master
kotti-gabriel===0.1.dev0dev-r0
-e git+git@github.com:Kotti/kotti_navigation.git@44ebbc939ccc7126951de65ca94d122b83876eb5#egg=kotti_navigation-master
kotti-settings==0.2
kotti-tinymce==0.5.1
```

**Comment by msabramo** [comment]
```
moduleOrReq == <module 'kotti_navigation' from '/Users/marca/dev/git-repos/kotti_navigation/kotti_navigation/__init__.pyc'>
```

**Comment by msabramo** [comment]
I just did a `git bisect` on this:

```
git bisect start
git bisect master
git bisect good 0.3.x
...
```

It concluded that 7d34e2d8f386178f3edcb9a5d8b72204ccc5fa91 introduced this behavior.

**Comment by msabramo** [comment]
I haven't quite been able to figure this one out yet.

Right now I'm having to use my own fork of the 0.3.x branch to get things working with a newish Kotti. 

It would be cool to fix this so I can use an official kotti_navigation instead of a fork.

**Comment by j23d** [comment]
Is this still an issue? How can I reproduce it?

**Comment by msabramo** [comment]
I can't reproduce this with a brand new virtualenv. I'm still getting it with my original virtualenv, so it must be something wrong in the virtualenv.

**Comment by msabramo** [comment]
I just reproduced the issue, though I don't know yet whether the issue is with kotti_navigation or pyramid.

The error does **not** happen for me with `pyramid==1.5.2`, but it happens for me with the latest pyramid from the `master` branch, which will probably become `pyramid==1.6.0` in a few months.

```
[marca@marca-mac2 ~VIRTUAL_ENV]$ pip freeze | egrep -i 'pyramid|kotti'
Warning: cannot find svn location for kotti-gabriel===0.1.dev0dev-r0
Kotti==1.0.0a4
kotti-contentpreview==0.1
kotti-gabriel===0.1.dev0dev-r0
-e git+git@github.com:Kotti/kotti_navigation.git@3d5441c163064407bb37146359d4a1de235b12dc#egg=kotti_navigation-master
kotti-settings==0.2
kotti-tinymce==0.5.1
-e git+https://github.com/Pylons/pyramid.git@99bf8b84fbadf5c50232fc90ee2cdc5708b6f6bf#egg=pyramid-master
pyramid-beaker==0.8
pyramid-chameleon==0.3
pyramid-debugtoolbar==2.3
pyramid-deform==0.2
pyramid-mailer==0.14
pyramid-mako==1.0.2
pyramid-tm==0.11
pyramid-zcml==1.0.0
```

I'm wondering if you can reproduce this if you use the `master` branch of pyramid?

**Comment by msabramo** [comment]
```pytb
2015-02-19 10:45:51,965 ERROR [Dummy-1][pyramid_debugtoolbar.toolbar_tween][toolbar.py +195] Exception at http://localhost:5000/
traceback url: http://localhost:5000/_debug_toolbar/exception?token=8ee7c5653c5eb958168c&tb=4442569872
Traceback (most recent call last):
  File "/Users/marca/python/virtualenvs/kotti_inventorysvc/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 178, in toolbar_tween
    response = _handler(request)
  File "/Users/marca/python/virtualenvs/kotti_inventorysvc/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/Users/marca/dev/git-repos/pyramid/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/Users/marca/python/virtualenvs/kotti_inventorysvc/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 94, in tm_tween
    reraise(*exc_info)
  File "/Users/marca/python/virtualenvs/kotti_inventorysvc/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 75, in tm_tween
    response = handler(request)
  File "/Users/marca/dev/git-repos/pyramid/pyramid/router.py", line 164, in handle_request
    response = view_callable(context, request)
  File "/Users/marca/dev/git-repos/pyramid/pyramid/config/views.py", line 383, in viewresult_to_response
    result = view(context, request)
  File "/Users/marca/python/virtualenvs/kotti_inventorysvc/lib/python2.7/site-packages/kotti/views/view.py", line 24, in view_content_default
    response = render_view_to_response(context, request, name=view_name)
  File "/Users/marca/dev/git-repos/pyramid/pyramid/view.py", line 60, in render_view_to_response
    return view(context, request)
  File "/Users/marca/dev/git-repos/pyramid/pyramid/config/views.py", line 243, in _secured_view
    return view(context, request)
  File "/Users/marca/dev/git-repos/pyramid/pyramid/config/views.py", line 375, in rendered_view
    context)
  File "/Users/marca/dev/git-repos/pyramid/pyramid/renderers.py", line 417, in render_view
    return self.render_to_response(response, system, request=request)
  File "/Users/marca/dev/git-repos/pyramid/pyramid/renderers.py", line 440, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/Users/marca/dev/git-repos/pyramid/pyramid/renderers.py", line 420, in render
    renderer = self.renderer
  File "/Users/marca/dev/git-repos/pyramid/pyramid/decorator.py", line 37, in __get__
    val = self.wrapped(inst)
  File "/Users/marca/dev/git-repos/pyramid/pyramid/renderers.py", line 404, in renderer
    return factory(self)
  File "/Users/marca/python/virtualenvs/kotti_inventorysvc/lib/python2.7/site-packages/pyramid_chameleon/zpt.py", line 10, in renderer_factory
    return renderer.template_renderer_factory(info, ZPTTemplateRenderer)
  File "/Users/marca/python/virtualenvs/kotti_inventorysvc/lib/python2.7/site-packages/pyramid_chameleon/renderer.py", line 140, in template_renderer_factory
    return lookup(info)
  File "/Users/marca/python/virtualenvs/kotti_inventorysvc/lib/python2.7/site-packages/pyramid_chameleon/renderer.py", line 115, in __call__
    filename)
  File "/Users/marca/python/virtualenvs/kotti_inventorysvc/lib/python2.7/site-packages/pkg_resources.py", line 959, in resource_filename
    self, resource_name
  File "/Users/marca/dev/git-repos/pyramid/pyramid/config/assets.py", line 31, in get_resource_filename
    filename = overrides.get_filename(resource_name)
  File "/Users/marca/dev/git-repos/pyramid/pyramid/config/assets.py", line 125, in get_filename
    result = source.get_filename(path)
  File "/Users/marca/dev/git-repos/pyramid/pyramid/config/assets.py", line 224, in get_filename
    if pkg_resources.resource_exists(self.package, path):
  File "/Users/marca/python/virtualenvs/kotti_inventorysvc/lib/python2.7/site-packages/pkg_resources.py", line 948, in resource_exists
    return get_provider(package_or_requirement).has_resource(resource_name)
  File "/Users/marca/python/virtualenvs/kotti_inventorysvc/lib/python2.7/site-packages/pkg_resources.py", line 225, in get_provider
    __import__(moduleOrReq)
TypeError: __import__() argument 1 must be string, not module
```

**Comment by msabramo** [comment]
The problem goes away if I comment out `kotti_navigation.kotti_configure` in my `app.ini` -- I get the error if I have:

```ini
kotti.configurators =
    kotti_settings.kotti_configure
    kotti_navigation.kotti_configure
```

but if I comment out `kotti_navigation.kotti_configure`:

```ini
kotti.configurators =
    kotti_settings.kotti_configure
;    kotti_navigation.kotti_configure
```

then the problem goes away.

**Comment by msabramo** [comment]
Hmmm, the problem also seems to go away if I comment out the asset overrides in `kotti_navigation`:

```diff
diff --git a/kotti_navigation/__init__.py b/kotti_navigation/__init__.py
index 6640223..17ee058 100644
--- a/kotti_navigation/__init__.py
+++ b/kotti_navigation/__init__.py
@@ -9,7 +9,7 @@ def kotti_configure(settings):
     settings['pyramid.includes'] += ' kotti_navigation.include_navigation deform_bootstrap js.deform'
     settings['kotti.populators'] += ' kotti_navigation.populate.populate'
     # We override nav.pt.
-    settings['kotti.asset_overrides'] += ' kotti_navigation:kotti-overrides/'
+    # settings['kotti.asset_overrides'] += ' kotti_navigation:kotti-overrides/'


 def include_navigation(config):  # pragma: no cover
```

**Comment by msabramo** [comment]
I wonder if there is a problem in the way that Kotti is calling [`pyramid.config.override_asset`](http://docs.pylonsproject.org/docs/pyramid/en/latest/api/config.html#pyramid.config.Configurator.override_asset)

**Comment by msabramo** [comment]
I think this is a pyramid bug.

**Comment by msabramo** [comment]
See https://github.com/Pylons/pyramid/pull/1587

**Comment by msabramo** [comment]
I'm going to close this, since this is definitely a Pyramid bug and hopefully Pylons/pyramid#1587 will get merged soon.

**Comment by j23d** [comment]
A lot of thanks for your investigation on this issue and the fix for pyramid, that is already merged!
